### ISSUE TITLE
Title page and colophon should never have double line spacing

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-nlb#41]
The NLB CSS currently looks like this:

``` css
@if $line-spacing == double {
   @page:left  {
      margin-top: 1; 
   }      
}
```

and in the generic dtbook-to-pef CSS we have:

``` css
@if $line-spacing == double {
   :root {
      line-height: 2;
   }   
}
```

I guess the NLB CSS should have something like this instead (not verified!):

``` css
@if $line-spacing == double {
   :root {
      line-height: 1; /* to cancel out generic rule*/
   }   
   bodymatter, level1[epub|type~='bodymatter'] {
      line-height: 2;
   }
   @page body:left  {
      margin-top: 1; 
   }      
}
```
